Vagrant.configure("2") do |config|

    config.vm.define "srv01" do |subconfig|
        subconfig.vm.box = "generic/ubuntu2004"
        subconfig.vm.hostname = "srv01"
        subconfig.vm.provider "hyperv"
        subconfig.vm.network "public_network", bridge: "External Switch"

        subconfig.vm.provider "hyperv" do |hyperv|
            hyperv.enable_virtualization_extensions = false
            hyperv.linked_clone = false
            hyperv.vmname = "ubuntu_test_machine"
        end

        subconfig.vm.provision "ansible" do |ansible|
            ansible.verbose = "v"
            ansible.playbook = "playbook.yaml"
        end
    end
end
